# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/espressif/conventional-precommit-linter
      rev: v1.3.0
      hooks:
          - id: conventional-precommit-linter
            stages: [commit-msg]
            args:
                - --types=feat,wip,fix,refactor,revert,merge
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
